server.port=4040
spring.application.name=IETScroll
server.admin.email=${ADMIN_EMAIL}
server.address=0.0.0.0
app.self-url=https://iet-scroll.onrender.com

#Database
spring.datasource.url=${SUPABASE_DB_URL}
#spring.datasource.username=postgres
#For deploymenet
spring.datasource.username=postgres.tuejfxqyrypbbmfvgole
spring.datasource.password=${SUPABASE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
# Hikari (Supabase optimized)
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.max-lifetime=300000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.connection-test-query=SELECT 1


#AI for content checking
spring.ai.openai.api-key=${NVIDIA_MISTRAL_KEY}
spring.ai.openai.base-url=https://integrate.api.nvidia.com
spring.ai.openai.chat.options.model=mistralai/mistral-small-4-119b-2603

#AI for resume rating
spring.ai.openai.api-llama-key=${NVIDIA_LLAMA_KEY}

#JWT
jwt.secret=${JWT_SECRET}

#actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

#Email
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#Images
cloudinary.cloud-name = ${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key = ${CLOUDINARY_API_KEY}
cloudinary.api-secret = ${CLOUDINARY_API_SECRET}

#Verification of image
sightengine.api-user = ${SIGHTENGINE_API_USER}
sightengine.api-secret = ${SIGHTENGINE_API_SECRET}
sightengine.api-url=https://api.sightengine.com/1.0/check.json
